name: build_docker_image

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  build_docker_image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Create .env
        run: touch .env

      - name: Set .env variables
        run: |
          echo "DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}" >> .env
          echo "DOCKER_IMAGE_TAG=${{ secrets.DOCKER_IMAGE_TAG }}" >> .env

      - name: Build
        run: sh dh build

      - name: Push
        run: sh dh push